# Generated by Django 4.2 on 2023-04-21 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0003_remove_task_tag_task_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "deadline"]},
        ),
    ]
