# Generated by Django 4.2 on 2023-04-21 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0004_alter_task_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="fact_date",
        ),
    ]
