# Generated by Django 4.2 on 2023-04-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0005_remove_task_fact_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tag", to="to_do_list.tag"),
        ),
    ]
