# Generated by Django 4.2 on 2023-04-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0006_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tasks", to="to_do_list.tag"),
        ),
    ]
