# Generated by Django 4.2 on 2023-04-26 00:10

from django.db import migrations


def forwards_func(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'fixture_data.json')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0007_alter_task_tags"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
