# Generated by Django 4.2 on 2023-04-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0008_auto_20230426_0310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(default="Add the task description!"),
        ),
    ]
